Restreserve/urls.py
from django.contrib import admin
from django.urls import path
from restapp import views
from django.contrib.auth import views as auth
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('register/',views.register,name='register'),
    path('login/',views.Login,name='login'),
    path('ownerhome/',views.ownerhome,name="ownerhome"),
    path('userhome/',views.userhome,name="userhome"),
    path('logout/',auth.LogoutView.as_view(template_name = 'index.html'),name="logout"),
    path('bookingstatus/',views.bookingstatus,name='bookingstatus'),
    path('bookingstatus-user/',views.bookingstatus_for_user, name='bookingstatus_for_user_url'),
    path('contact/',views.contact,name='contact'),
    path('delete/<int:id>',views.delete),
    path('delete1/<int:id>',views.delete1),
    path('delete2/<int:id>',views.delete2),
    path('edit/<int:id>',views.update, name="edit_url"),
    path('update/<int:id>',views.edit),


    path('Details',views.Details,name='Details'),
    path('Addrestdetails',views.Addrestdetails,name='Addrestdetails'),
    # path('editdetails',views.editdetails,name='editdetails'),

]

restapp/models.py
from django.db import models


from django.contrib.auth.models import User

# Create your models here.
class bookingdetails(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    time = models.TimeField()
    date = models.DateField()
    totalpeople = models.CharField(max_length=10)
    class Meta:
        db_table ="bookingdetails"

class contactdetails(models.Model):
    Name = models.CharField(max_length=50)
    Phone = models.CharField(max_length=11)
    Email = models.EmailField()
    Subject = models.TextField(max_length=50)
    class Meta:
        db_table = "contactdetails"
        

class restdetails(models.Model):
    special = models.CharField(max_length=60)
    opentime = models.TimeField()
    closetime = models.TimeField()
    class Meta:
        db_table = "restdetails"

restapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from restapp.models import bookingdetails,contactdetails,restdetails

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(max_length=20,widget=forms.TextInput(attrs={'type': 'char', 'class':'form-control form-control' ,'placeholder': 'username'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'type': 'char', 'class':'form-control form-control' ,'placeholder': 'Email'}))
    phone_no = forms.CharField(max_length=20 ,widget=forms.TextInput(attrs={'type': 'char', 'class':'form-control form-control' ,'placeholder': 'Enter Your Phone'}))
    first_name = forms.CharField(max_length=20,widget=forms.TextInput(attrs={'type': 'char', 'class':'form-control form-control' ,'placeholder': 'Enter Your First Name'}))
    last_name = forms.CharField(max_length=20,widget=forms.TextInput(attrs={'type': 'char', 'class':'form-control form-control' ,'placeholder': 'Enter Your Last Name'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control','placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control','placeholder': 'confirm Password'}))
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class bookingdetailsform(forms.ModelForm):
    time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time', 'class':'form-control timepicker'}))
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class':'form-control datepicker'}))
    totalpeople = forms.CharField(widget=forms.TextInput(attrs={'type': 'char', 'class':'form-control form-control' ,'placeholder': 'totalpeople'}))

    class Meta:
        model = bookingdetails
        fields = ['time','date','totalpeople']

class contactdetailsform(forms.ModelForm):
    Name = forms.CharField(widget=forms.TextInput(attrs={'type': 'char', 'class':'form-control form-control' ,'placeholder': 'Name'}))
    Phone = forms.CharField(widget=forms.TextInput(attrs={'type': 'char', 'class':'form-control form-control' ,'placeholder': 'Phone'}))
    Email = forms.EmailField(widget=forms.TextInput(attrs={'type': 'char', 'class':'form-control form-control' ,'placeholder': 'Email'}))
    # Subject = forms.TextField(widget=forms.TextInput(attrs={'type': 'Text', 'class':'form-control form-control' ,'placeholder': 'totalpeople'}))


    class Meta:
        model = contactdetails
        fields = ['Name','Phone','Email','Subject']
    
class restdetailsform(forms.ModelForm):
    special = forms.CharField(widget=forms.TextInput(attrs={'type': 'char', 'class':'form-control form-control' ,'placeholder': 'special'}))
    opentime = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time', 'class':'form-control timepicker'}))
    closetime = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time', 'class':'form-control timepicker'}))


    class Meta:
        model = restdetails
        fields = ['special','opentime','closetime']

restapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserRegisterForm,bookingdetailsform,contactdetailsform,restdetailsform
from django.contrib import messages

from django.contrib.auth.decorators import login_required

from restapp.models import bookingdetails,contactdetails,restdetails

# Create your views here.

def index(request):
    contform = contactdetailsform()
    if request.method =='POST':
        contform = contactdetailsform(request.POST)
        if contform.is_valid():
            contform.save()
            messages.success(request,'Confirmed Your Request')
            return redirect('index')
    else:
        contform = contactdetailsform()

    return render(request,'index.html',{'contform':contform})

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request,'Account is created')
                return redirect('index')
            except:
                pass

    else:
        form = UserRegisterForm()
    return render(request,'register.html',{'form':form})

def Login(request):
    #  if request.method == 'POST':
    #     username = request.POST['username']
    #     password = request.POST['password']

    #     user = authenticate(username=username, password=password)

    #     if user is not None:
    #         if user.is_staff == True:
    #             return redirect('ownerhome')
    #         else:
    #             form =login(request,user)
    #             messages.success(request,f'welcome {username} !!')
    #             return redirect('userhome')
    #     else:
    #         messages.info(request, 'invalid username and password')
    #         return redirect('login')
       
    #  else:
    #     return render(request,'Login.html')
    if request.method =='POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,username = username,password = password)
        if user is not None:
            if user.is_staff == True:
                return redirect('ownerhome')
            else:
                form = login(request,user)
                messages.success(request,f'welcome {username} !!')
                return redirect('userhome') 
        else:
            messages.info(request,'account done not exit plz sign in')
            
    form = AuthenticationForm()
    return render(request,'Login.html',{'form':form})


@login_required()
def userhome(request):
    form1 = bookingdetailsform()
    if request.method == 'POST':
        form1 = bookingdetailsform(request.POST)
        if form1.is_valid:
            try:
                profile = form1.save(commit=False)
                profile.user = request.user
                profile.save()
                # form1.save()
                messages.success(request,'Your booking is pending!!!  Check your Email or SMS for conformation')
                return redirect('userhome')
            except:
                pass
    else:
        form1 = bookingdetailsform()


    return render(request,'userhome.html',{'form1':form1})


def ownerhome(request):
    return render(request,'ownerhome.html')

def bookingstatus(request):

    booking = bookingdetails.objects.all()
    
    return render(request,'bookingstatus.html',{'booking':booking})

def bookingstatus_for_user(request):

    cont1 = restdetails.objects.all()

    return render(request,'bookingstatus-user.html',{'cont1':cont1})


def contact(request):

    cont = contactdetails.objects.all()

    return render(request,'contact.html',{'cont':cont})

def delete(request,id):
    booking = bookingdetails.objects.get(id=id)
    booking.delete()
    return redirect('/bookingstatus')

def delete1(request,id):
    cont = contactdetails.objects.get(id=id)
    cont.delete()
    return redirect('/contact')

def Details(request):
    contform = restdetailsform()
    if request.method =='POST':
        contform = restdetailsform(request.POST)
        if contform.is_valid():
            contform.save()
            messages.success(request,'Confirmed Your Request')
            return redirect('Details')
    else:
        contform = restdetailsform()
    return render(request,'Details.html',{'contform' : contform})

def Addrestdetails(request):

    cont1 = restdetails.objects.all()

    return render(request,'Addrestdetails.html',{'cont1':cont1})

def delete2(request,id):
    cont = restdetails.objects.get(id=id)
    cont.delete()
    return redirect('/Addrestdetails')


def edit(request,id):

    rest = restdetails.objects.get(id=id)

    return render(request,'editdetails.html',{'rest':rest})

def update(request,id):
    rest = restdetails.objects.get(id=id)
    if request.method == 'POST':
        special = request.POST['special']
        opentime = request.POST['opentime']
        closetime = request.POST['closetime']
        print("-------------------------------------", special, opentime, closetime)
        rest.special = special
        rest.opentime = opentime
        rest.closetime = closetime
        rest.save()
        return redirect("Addrestdetails")

    return render(request,"editdetails.html",{'rest':rest})

restapp/templates/Addrestdetails.html
<!DOCTYPE html>
<html lang="en">

</html>

<head>
    <title>bookingdetails</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="{%url 'ownerhome' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div class="caption">
        <div class="headfont">
            <center>
                <h1><b><u>Adddetails</u></b></h1>
            </center>

        </div>
    </div>
    <div class="container">
        <table class="table table-sriped table-bordered table-sm">
            <thead class="thead-dark">
                <tr>
                    <th>Special</th>
                    <th>Opentime</th>
                    <th>Closetime</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for restdetails in cont1 %}
                <tr>
                    <td>{{restdetails.special}}</td>
                    <td>{{restdetails.opentime}}</td>
                    <td>{{restdetails.closetime}}</td>

                    <td>
                        <a href="{% url 'edit_url' restdetails.id%}"><span class="glyphicon glyphicon-penci">Edit</span></a>
                        <a href="/delete2/{{restdetails.id}}">Delete</a>

                    </td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

restapp/templates/Details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>contact</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/details.css' %}" type="text/css" media="all" />


</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="{%url 'ownerhome' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div class="caption">
        <div class="headfont">
            <center>
                <h1><b><u>Restaurent Details</u></b></h1>
            </center><br>
            <br>

        </div>
    </div>
    <div>
        <form action="" method="post">
            {% csrf_token%}
            <div class="container">
                <div align="center">

                    {{contform.special}}<br>
                    {{contform.special.errors}}


                    {{contform.opentime}}<br>
                    {{contform.opentime.errors}}


                    {{contform.closetime}}<br>
                    {{contform.closetime.errors}}

                    <div align="center">

                        <input class="btn btn-dark" type="submit" value="Submit" style="margin-left: 40px;">
                    </div>
                </div>
            </div>

    </div>


</body>

</html>

restapp/templates/bookingstatus-user.html
<!DOCTYPE html>
<html lang="en">

</html>

<head>
    <title>bookingdetails</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="{%url 'userhome' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div class="caption">
        <div class="headfont">
            <center>
                <h1><b><u>Adddetails</u></b></h1>
            </center>

        </div>
    </div>
    <div class="container">
        <table class="table table-sriped table-bordered table-sm">
            <thead class="thead-dark">
                <tr>
                    <th>Special</th>
                    <th>Opentime</th>
                    <th>Closetime</th>
                </tr>
            </thead>
            <tbody>
                {% for restdetails in cont1 %}
                <tr>
                    <td>{{restdetails.special}}</td>
                    <td>{{restdetails.opentime}}</td>
                    <td>{{restdetails.closetime}}</td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

restapp/templates/bookingstatus.html
<!DOCTYPE html>
<html lang="en">

</html>

<head>
    <title>bookingdetails</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="{%url 'ownerhome' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div class="caption">
        <div class="headfont">
            <center>
                <h1><b><u>Bookingdetails</u></b></h1>
            </center>

        </div>
    </div>
    <div class="container">
        <table class="table table-sriped table-bordered table-sm">
            <thead class="thead-dark">
                <tr>
                    <th>User</th>
                    <th>time</th>
                    <th>date</th>
                    <th>No.of Visiters</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for bookingdetails in booking %}
                <tr>
                    <td>{{bookingdetails.user.email}}</td>
                    <td>{{bookingdetails.time}}</td>
                    <td>{{bookingdetails.date}}</td>
                    <td>{{bookingdetails.totalpeople}}</td>

                    <td>
                        <a href="/Confirm/{{bookingdetails.id}}"><span
                                class="glyphicon glyphicon-penci">Confirm</span></a>
                        <a href="/delete/{{bookingdetails.id}}">Cancel</a>

                    </td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

restapp/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

</html>

<head>
    <title>contact</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="{%url 'ownerhome' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div class="caption">
        <div class="headfont">
            <center>
                <h1><b><u>Contact</u></b></h1>
            </center>

        </div>
    </div>
    <div class="container">
        <table class="table table-sriped table-bordered table-sm">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Subject</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for contactdetails in cont %}
                <tr>
                    <td>{{contactdetails.Name}}</td>
                    <td>{{contactdetails.Phone}}</td>
                    <td>{{contactdetails.Email}}</td>
                    <td>{{contactdetails.Subject}}</td>

                    <td>
                        <a href="/delete1/{{contactdetails.id}}">delete</a>

                    </td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

restapp/templates/editdetails.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>index</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <h1 align="center">Update Details</h1><br>
            <!-- 2 column grid layout with text inputs for the first and last names -->
            <!-- Text input -->
            <div class="form-outline mb-4">
                <input type="text" name="special" id="id_special" required maxlength="20" value="{{rest.special}}"/><br>
                <label class="form-label" for="id_special">Name</label>
            </div>
            <div class="form-outline mb-4">
                <input type="time" name="opentime" id="id_opentime" required maxlength="100" value="{{rest.opentime}}"/><br>
                <label class="form-label" for="id_opentime">open time</label>
            </div>
            <div class="form-outline mb-4">
                <input type="time" name="closetime" id="id_closetime" required maxlength="254" value="{{rest.closetime}}"/><br>
                <label class="form-label" for="id_closetime">close time</label>
            </div>
            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block mb-4">Update</button>
        </form>
    </div>
    
</body>
</html>

restapp/templates/index.html
{% load static %}
<!-- <!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Home</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>

<body>
    <a href="{% url 'login' %}">login</a>
    <a href="{% url 'register' %}">register</a>
</body>

</html> -->





<!DOCTYPE html>
<html lang="en">

</html>

<head>
    <title>Index</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/indexstyle.css' %}" type="text/css" media="all" />




</head>

<body>
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="{%url 'index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span> -->



    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-transparent p-4 fixed-top">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link  text-white" href="{%url 'index' %}">Home <span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link text-white" href="{% url 'login' %}" style="padding-left: 1198px;">Login</a>
                    </li>

                    <li class="nav-item" id="navstyle">
                        <a class="nav-link text-white" href="{% url 'register' %}">Register</a>
                    </li>

                    <li class="nav-item" id="navstyle">
                        <a class="nav-link text-white" href="#contact">Contact Us</a>
                    </li>

                </ul>
            </div>
        </nav>
    </div>



    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'image1/b6.jpg' %}" alt="My image" class="d-block w-100" height="755px">
            </div>
            <div class="carousel-caption d-none d-md-block">
                <h1>Online Restaurant Reservation</h1>
            </div>
        </div>
    </div>







    <!-- <div class="contact" id="contact">
        <div class="container">
            <div >
                <div class="contheading">
                    <h4>Contact Us</h4>
                </div>
                <div class="contdetails">
                    <form action="" method="post">
                        {% csrf_token %}

                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Name</label>
                            <div class="col-sm-10">
                                {{contform.Name}}

                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Phone</label>
                            <div class="col-sm-10">
                                {{contform.Phone}}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                            <div class="col-sm-10">
                                {{contform.Email}}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Subject</label>
                            <div class="col-sm-10">
                                {{contform.Subject}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Send</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

 -->


    <div class="contact" id="contact">
        <form action="" method="post">
            {% csrf_token%}
            <div class="container">
                <div align="center">
                    <div class="contact-class">
                        <h2>Contact Us</h2>
                    </div>
                    <br>
                    {{contform.Name }}<br>
                    {{contform.Name.errors}}

                    <br>
                    {{contform.Phone}}<br>
                    {{contform.date.Phone}}

                    <br>
                    {{contform.Email}}<br>
                    {{contform.Email.errors}}

                    <label>Subject</label><br>
                    {{contform.Subject}}<br>
                    {{contform.Subject.errors}}

                </div>
                <div align="center">
                    <input class="btn btn-success" type="submit" value="Submit">
                </div>
            </div>
    </div>

</body>

</html>